package core

import mock "github.com/stretchr/testify/mock"

// MockSettings is an autogenerated mock type for the Settings type
type MockSettings struct {
	mock.Mock
}

// GetTemplates provides a mock function with given fields:
func (_m *MockSettings) GetTemplates() (map[string]Template, error) {
	ret := _m.Called()

	var r0 map[string]Template
	if rf, ok := ret.Get(0).(func() map[string]Template); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Template)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveTemplate provides a mock function with given fields: name, tpl
func (_m *MockSettings) SaveTemplate(name string, tpl Template) error {
	ret := _m.Called(name, tpl)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, Template) error); ok {
		r0 = rf(name, tpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ Settings = (*MockSettings)(nil)
