package core

import mock "github.com/stretchr/testify/mock"

// MockFormatter is an autogenerated mock type for the Formatter type
type MockFormatter struct {
	mock.Mock
}

// Format provides a mock function with given fields: row
func (_m *MockFormatter) Format(row Row) string {
	ret := _m.Called(row)

	var r0 string
	if rf, ok := ret.Get(0).(func(Row) string); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

var _ Formatter = (*MockFormatter)(nil)
