package core

import mock "github.com/stretchr/testify/mock"

// MockFilterFactory is an autogenerated mock type for the FilterFactory type
type MockFilterFactory struct {
	mock.Mock
}

// NewFilter provides a mock function with given fields: condition
func (_m *MockFilterFactory) NewFilter(condition string) (Filter, error) {
	ret := _m.Called(condition)

	var r0 Filter
	if rf, ok := ret.Get(0).(func(string) Filter); ok {
		r0 = rf(condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Filter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ FilterFactory = (*MockFilterFactory)(nil)
