package core

import mock "github.com/stretchr/testify/mock"

// MockFilter is an autogenerated mock type for the Filter type
type MockFilter struct {
	mock.Mock
}

// Match provides a mock function with given fields: row
func (_m *MockFilter) Match(row Row) bool {
	ret := _m.Called(row)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Row) bool); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

var _ Filter = (*MockFilter)(nil)
